namespace SpriteKind {
    export const NPC1 = SpriteKind.create()
    export const NPC2 = SpriteKind.create()
    export const NPC3 = SpriteKind.create()
    export const NPC4 = SpriteKind.create()
    export const NPC5 = SpriteKind.create()
    export const NPC6 = SpriteKind.create()
    export const Enemy1 = SpriteKind.create()
    export const Enemy2 = SpriteKind.create()
    export const Enemy3 = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`yellow`, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`Chichen Itza`)
    tiles.placeOnRandomTile(Gamer, sprites.dungeon.collectibleInsignia)
    Chichen_Itza_Guide = sprites.create(assets.image`Chichen Itza Guide`, SpriteKind.NPC3)
    tiles.placeOnTile(Chichen_Itza_Guide, tiles.getTileLocation(5, 4))
    game.showLongText("Level-3: Chichen Itza - Find the Guide to know about Chichen Itza", DialogLayout.Full)
    game.showLongText("NOTE:- BE CAREFUL! There are few enemies which have Red Robes.", DialogLayout.Full)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy1, function (sprite, otherSprite) {
    tiles.setTileAt(tiles.getTileLocation(6, 5), sprites.dungeon.floorDark2)
    tiles.setTileAt(tiles.getTileLocation(7, 6), sprites.dungeon.floorDark2)
    tiles.setWallAt(tiles.getTileLocation(6, 5), true)
    tiles.setWallAt(tiles.getTileLocation(7, 6), true)
    Enemy1.sayText("Ha Ha Ha You are trapped. You are being teleported to the starting point", 5000, false)
    pause(2000)
    Enemy1.sayText("Bye Bye", 1000, false)
    pause(2000)
    tiles.placeOnRandomTile(Gamer, sprites.dungeon.collectibleBlueCrystal)
    Enemy1.destroy()
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy3, function (sprite, otherSprite) {
    tiles.setTileAt(tiles.getTileLocation(3, 21), sprites.dungeon.floorDark2)
    tiles.setWallAt(tiles.getTileLocation(3, 21), true)
    Enemy_3.sayText("Ha Ha Ha You are trapped. You are being teleported to the starting point", 5000, false)
    pause(2000)
    Enemy_3.sayText("Bye Bye", 1000, false)
    pause(2000)
    tiles.placeOnRandomTile(Gamer, sprites.dungeon.stairLadder)
    Enemy_3.destroy()
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC5, function (sprite, otherSprite) {
    Christ_The_Redeemer_Guide.sayText("Do you know about Christ The Redeemer?", 4000, false)
    pause(6000)
    Gamer.sayText("No, I want to know about it.", 5000, false)
    pause(6000)
    Christ_The_Redeemer_Guide.sayText("Christ The Redeemer is one of the 7 Wonders of the World.", 5000, false)
    pause(6000)
    Christ_The_Redeemer_Guide.sayText("It was created by french sculptor Paul Landowski and built by Brazilian engineer Heitor da Silva Costa", 5000, false)
    pause(6000)
    Gamer.sayText("Thanks for giving me the information about it", 5000, false)
    pause(6000)
    Christ_The_Redeemer_Guide.sayText("Welcome! Find an Pink tile to win the game", 8000, false)
    pause(9000)
    Christ_The_Redeemer_Guide.destroy()
    tiles.setTileAt(tiles.getTileLocation(12, 1), assets.tile`pink`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`pink`, function (sprite, location) {
    game.over(true, effects.confetti)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC2, function (sprite, otherSprite) {
    Colosseum_Guide.sayText("Do you know about Colosseum?", 4000, false)
    pause(6000)
    Gamer.sayText("No", 2000, false)
    pause(3000)
    Colosseum_Guide.sayText("Do you want to know about it? (press B for 8 sec to Skip)", 7000, false)
    pause(8000)
    if (controller.B.isPressed()) {
        Colosseum_Guide.sayText("Welcome! Find an Yellow tile to go in the next level to know about another monument", 8000, false)
        tiles.setTileAt(tiles.getTileLocation(16, 1), assets.tile`yellow`)
        tiles.setTileAt(tiles.getTileLocation(33, 2), sprites.builtin.brick)
        tiles.setWallAt(tiles.getTileLocation(33, 2), false)
        pause(6000)
        Colosseum_Guide.destroy()
    } else {
        Gamer.sayText("Yes.", 5000, false)
        pause(6000)
        Colosseum_Guide.sayText("Colosseum is one of the 7 Wonders of the World.", 5000, false)
        pause(6000)
        Colosseum_Guide.sayText("It was built during the reign of Vespasian during 70-72 CE under the Flavian emperor", 5000, false)
        pause(6000)
        Gamer.sayText("Thanks for giving me the information about it", 5000, false)
        pause(6000)
        Colosseum_Guide.sayText("Welcome! Find an Yellow tile to go in the next level to know about another monument", 8000, false)
        tiles.setTileAt(tiles.getTileLocation(0, 14), assets.tile`yellow`)
        tiles.setTileAt(tiles.getTileLocation(33, 2), sprites.builtin.brick)
        tiles.setWallAt(tiles.getTileLocation(33, 2), false)
        pause(9000)
        Colosseum_Guide.destroy()
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC3, function (sprite, otherSprite) {
    Chichen_Itza_Guide.sayText("Do you know about Chichen Itza?", 4000, false)
    pause(6000)
    Gamer.sayText("No", 2000, false)
    pause(3000)
    Chichen_Itza_Guide.sayText("Do you want to know about it? (press B for 8 sec to Skip)", 8000, false)
    pause(9000)
    if (controller.B.isPressed()) {
        Chichen_Itza_Guide.sayText("Welcome! Find an Red tile to go in the next level to know about another monument", 8000, false)
        tiles.setTileAt(tiles.getTileLocation(1, 11), assets.tile`red`)
        pause(9000)
        Chichen_Itza_Guide.destroy()
    } else {
        Chichen_Itza_Guide.sayText("Yes", 2000, false)
        pause(3000)
        Chichen_Itza_Guide.sayText("Chichen Itza is one of the 7 Wonders of the World.", 5000, false)
        pause(6000)
        Chichen_Itza_Guide.sayText("It was a large pre-Columbian city built by the maya people of Terminal Classic Period  ", 5000, false)
        pause(6000)
        Gamer.sayText("Thanks for giving me the information about it", 5000, false)
        pause(6000)
        Chichen_Itza_Guide.sayText("Welcome! Find an Red tile to go in the next level to know about another monument", 8000, false)
        tiles.setTileAt(tiles.getTileLocation(1, 11), assets.tile`red`)
        pause(9000)
        Chichen_Itza_Guide.destroy()
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC4, function (sprite, otherSprite) {
    Machu_Picchu_Guide.sayText("Do you know about Machu Picchu?", 4000, false)
    pause(6000)
    Gamer.sayText("No, I want to know about it.", 5000, false)
    pause(6000)
    Machu_Picchu_Guide.sayText("Machu Picchu is one of the 7 Wonders of the World.", 5000, false)
    pause(6000)
    Machu_Picchu_Guide.sayText("It was built above the Urubamba river valley by the incans during the 15th Century  ", 5000, false)
    pause(6000)
    Gamer.sayText("Thanks for giving me the information about it", 5000, false)
    pause(6000)
    Machu_Picchu_Guide.sayText("Welcome! Find an Cyan tile to go in the next level to know about another monument", 8000, false)
    pause(9000)
    Machu_Picchu_Guide.destroy()
    tiles.setTileAt(tiles.getTileLocation(1, 11), assets.tile`light blue`)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC1, function (sprite, otherSprite) {
    Taj_Mahal_Guide.sayText("Do you know about Taj Mahal?", 4000, false)
    pause(6000)
    Gamer.sayText("No.", 5000, false)
    pause(6000)
    Taj_Mahal_Guide.sayText("Do you want to know about it? (press B for 8 sec to Skip)", 7000, false)
    pause(8000)
    if (controller.B.isPressed()) {
        Taj_Mahal_Guide.sayText("Welcome! Find an Purple tile to go in the next level to know about another monument", 8000, false)
        tiles.setTileAt(tiles.getTileLocation(1, 1), assets.tile`purple`)
        pause(2000)
        Taj_Mahal_Guide.destroy()
    } else {
        Gamer.sayText("Yes.", 5000, false)
        pause(6000)
        Taj_Mahal_Guide.sayText("Taj Mahal is one of the 7 Wonders of the World.", 5000, false)
        pause(6000)
        Taj_Mahal_Guide.sayText("It was built by Emperor Shah Jahan for his loving wife Mumtaz Mahal", 5000, false)
        pause(6000)
        Gamer.sayText("Thanks for giving me the information about it", 5000, false)
        pause(6000)
        Taj_Mahal_Guide.sayText("Welcome! Find an Purple tile to go in the next level to know about another monument", 8000, false)
        tiles.setTileAt(tiles.getTileLocation(1, 1), assets.tile`purple`)
        pause(2000)
        Taj_Mahal_Guide.destroy()
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`light blue`, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`Christ The Redeemer`)
    tiles.placeOnRandomTile(Gamer, tiles.util.arrow0)
    Christ_The_Redeemer_Guide = sprites.create(assets.image`Christ The Redeemer Guide`, SpriteKind.NPC5)
    tiles.placeOnTile(Christ_The_Redeemer_Guide, tiles.getTileLocation(6, 5))
    game.showLongText("Level-5:Christ The Redeemer- Find the Guide to know about Christ The Redeemer", DialogLayout.Full)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`red`, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`Machu Picchu`)
    tiles.placeOnRandomTile(Gamer, sprites.dungeon.collectibleRedCrystal)
    Machu_Picchu_Guide = sprites.create(assets.image`Machu Picchu Guide`, SpriteKind.NPC4)
    tiles.placeOnTile(Machu_Picchu_Guide, tiles.getTileLocation(5, 4))
    game.showLongText("Level-4: Machu Picchu - Find the Guide to know about Machu Picchu", DialogLayout.Full)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy2, function (sprite, otherSprite) {
    tiles.setTileAt(tiles.getTileLocation(5, 27), sprites.dungeon.floorDark2)
    tiles.setTileAt(tiles.getTileLocation(7, 28), sprites.dungeon.floorDark2)
    tiles.setTileAt(tiles.getTileLocation(8, 27), sprites.dungeon.floorDark2)
    tiles.setWallAt(tiles.getTileLocation(5, 27), true)
    tiles.setWallAt(tiles.getTileLocation(7, 28), true)
    tiles.setWallAt(tiles.getTileLocation(8, 27), true)
    Enemy_2.sayText("Ha Ha Ha You are trapped. You are being teleported to the starting point", 5000, false)
    pause(2000)
    Enemy_2.sayText("Bye Bye", 1000, false)
    pause(2000)
    tiles.placeOnRandomTile(Gamer, sprites.dungeon.stairLadder)
    Enemy_2.destroy()
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`purple`, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`Colosseum`)
    Enemy1.destroy()
    tiles.placeOnRandomTile(Gamer, sprites.dungeon.stairLadder)
    Colosseum_Guide = sprites.create(assets.image`Colosseum Guide`, SpriteKind.NPC2)
    Enemy_2 = sprites.create(assets.image`Enemy`, SpriteKind.Enemy2)
    Enemy_3 = sprites.create(assets.image`Enemy`, SpriteKind.Enemy3)
    tiles.placeOnTile(Colosseum_Guide, tiles.getTileLocation(32, 23))
    tiles.placeOnTile(Enemy_2, tiles.getTileLocation(6, 27))
    tiles.placeOnTile(Enemy_3, tiles.getTileLocation(5, 22))
    game.showLongText("Level-2: Colosseum - Find the Guide to know about Colosseum", DialogLayout.Full)
    game.showLongText("NOTE:- BE CAREFUL! There are few enemies which have Red Robes.", DialogLayout.Full)
})
let Enemy_2: Sprite = null
let Machu_Picchu_Guide: Sprite = null
let Colosseum_Guide: Sprite = null
let Christ_The_Redeemer_Guide: Sprite = null
let Enemy_3: Sprite = null
let Chichen_Itza_Guide: Sprite = null
let Enemy1: Sprite = null
let Taj_Mahal_Guide: Sprite = null
let Gamer: Sprite = null
scene.setBackgroundImage(assets.image`Stage`)
let modak = sprites.create(assets.image`Boy`, SpriteKind.Player)
modak.setPosition(78, 87)
modak.sayText("Hi everyone!", 2000, true)
pause(2500)
modak.sayText("Today we are going to play a Interesting Game.", 8000, true)
pause(9000)
scene.setBackgroundImage(assets.image`4 Wonders of the World in 1 Image`)
modak.destroy()
let modak_2 = sprites.create(assets.image`Boy`, SpriteKind.Player)
modak_2.setPosition(53, 111)
modak_2.sayText("Topic:- Earth & World Cultural Heritage Preservation (Maze)", 7000, true)
pause(8000)
modak_2.sayText("So, Lets Start. ", 3000, true)
pause(4500)
modak_2.destroy()
tiles.setCurrentTilemap(tilemap`Taj Mahal`)
Gamer = sprites.create(assets.image`Boy`, SpriteKind.Player)
Taj_Mahal_Guide = sprites.create(assets.image`Taj Mahal`, SpriteKind.NPC1)
Enemy1 = sprites.create(assets.image`Enemy`, SpriteKind.Enemy1)
tiles.placeOnTile(Enemy1, tiles.getTileLocation(6, 7))
tiles.placeOnTile(Taj_Mahal_Guide, tiles.getTileLocation(3, 18))
controller.moveSprite(Gamer)
tiles.placeOnRandomTile(Gamer, sprites.dungeon.collectibleBlueCrystal)
scene.cameraFollowSprite(Gamer)
game.showLongText("Level-1: Taj Mahal - Find the Guide to know about Taj Mahal", DialogLayout.Full)
game.showLongText("NOTE:- 'BE CAREFUL! There are few enemies which have Red Robes.", DialogLayout.Full)
